path: v{{.Version}}/protoc-{{.Version}}-{{.Os}}{{.Arch | prefix "-"}}.zip
platforms:
  linux/_amd64/: linux/x86_64/
  linux/_arm64/: linux/aarch_64/
  windows/_amd32/: win32//
  windows/_amd64/: win64//
