#!/usr/bin/env bash

set -o errexit
set -o pipefail
# set -o xtrace

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"

APP_VERSION=${BUILD_VERSION:-"v0.0.0"}
BUILD_ID=${BUILD_ID:-"0"}

GIT_REV=${BUILD_HASH:-"0000000000000000000000000000000000000000"}
GIT_DIRTY="false"
if [ $(git rev-parse --is-inside-work-tree) ]; then
	GIT_REV=$(git rev-parse HEAD)
	GIT_DIRTY=$([ -n "$(git status --porcelain)" ] && echo "true" || echo "false")
fi

cd "$__root"

(cat | tee ./cmd/version.g.go) <<EOL
// Code generated by scripts/gen-version-file.sh. DO NOT EDIT.
package cmd

func init(){
	v := &_buildInfo
	v.Version = "$APP_VERSION"
	v.BuildId = "$BUILD_ID"
	v.GitRev = "$GIT_REV"
	v.GitDirty = $GIT_DIRTY
}
EOL
