path: v{{.Version}}/gh_{{.Version}}_{{.Os}}_{{.Arch}}.tar.gz
platforms:
  linux/_amd64/: linux/amd64/
  linux/_arm64/: linux/arm64/
  windows/_amd64/: windows/amd64/
  windows/_arm64/: windows/arm64/
  darwin/_amd64/: darwin/amd64/
  darwin/_arm64/: darwin/arm64/
---
path: v{{.Version}}/gh_{{.Version}}_{{.Os}}_{{.Arch}}.zip
platforms:
  windows/_amd64/: windows/amd64/
  windows/_arm64/: windows/arm64/
